# Copyright (C) 2016-2018 Betalo AB

language: go

notifications:
  email: false

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - 1.14.x
    - master

install: make deps

script: make test
